language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev"  # 3.5 development branch
  - "3.6"
  # - "3.6-dev"  # 3.6 development branch

addons:
  postgresql: "9.6"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - flake8 --exclude=migrations --ignore=F401,F402,F403,F405,E722,E741,E402,E721 --max-line-length=130
  - python3 manage.py test --settings=inkshop.envs.ci
services:
  - postgresql
  - memcached
