version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
        - image: circleci/python:3.6.8-node
        - image: circleci/postgres:9.6-alpine
          environment: 
            POSTGRES_HOST: localhost
            POSTGRES_USER: ubuntu
            POSTGRES_DB: circle_test
        - image: redis

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: 
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run: sudo pip install --upgrade pip
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: 
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      # - run: sudo npm i -g less
      - run: . venv/bin/activate && flake8 --exclude=migrations --ignore=F401,F402,F403,F405,E722,E741,E402,E721 --max-line-length=130
      - run: . venv/bin/activate && python3 manage.py test --settings=envs.ci


machine:
    python:
        version: 3.6.8
    services:
        - redis
