version: "3.2"

services:  
  traefik:
    image: traefik:1.7-alpine
    container_name: inkshop_traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=${INKSHOP_DOMAIN}"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@${INKSHOP_DOMAIN}"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./services/traefik/acme.json:/acme.json"
      - "./services/traefik/data:/traefik/acme/account"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  db:
    image: postgres
    ports:
     - 5432:5432
    env_file:
      - ".env"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    container_name: inkshop_redis
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    env_file:
      - ".env"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_LOGS: "/var/log/rabbitmq/rabbit.log"
    ports:
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  inkshop:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./inkshop:/project/inkshop
    labels:
      - "traefik.enable=true"
      - "traefik.port=8120"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host: ${INKSHOP_DOMAIN}"
      - "traefik.docker.network=inkshop"
    env_file:
      - ".env"
    command: bash -c 'service nginx start; cd /project; PYTHONIOENCODING="utf-8" python3 manage.py collectstatic --noinput --settings=inkshop.envs.dev; honcho start -f Procfile.dev'
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  default:
    external:
      name: inkshop

volumes:
  traefik:
    driver_opts:
      type: none
      device: /root/server-docker-images/data/traefik
      o: bind
  